### ISSUE TITLE
There is a bug that is preventing javascript to finish loading things

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx#228]
There is a bug that is preventing javascript to finish loading things, so there are some carousels not loading, the facets are not loading, and some admin usability is not loading.

**Comment by viscosho** [comment]
<img width="1310" alt="Screen Shot 2019-09-27 at 4 07 13 PM" src="https://user-images.githubusercontent.com/3129483/65795595-02f14180-e141-11e9-8b2f-db6d657f7431.png">
![Uploading Screen Shot 2019-09-27 at 4.07.03 PM.png…]()

**Comment by viscosho** [comment]
I have narrowed the issue to have an origin on this brach: https://github.com/lightspeeddevelopment/lsx/commit/26a66405a1743697212f533cd8c5b287ec344daa

**Comment by krugazul** [comment]
@viscosho and @ashleyshaw I have added in a SASS module for the slick slider,  the "theme" for slick was removed when i regenerated the CSS,  that is now fixed and the structure of the sliders are back.

w.r.t to the JS error in LSX,  that was due to the `scrollspy` and the `scroll easing` vendors being triggered on `document.ready`, I have moved those to `document.load`

The lsx demo site is loading,  Ive checked the blog link as well.   Ive also checked the LSX FMB site,  and the TO Demo site

**Comment by krugazul** [comment]
@viscosho did some testing, and picked up another bug,  I have removed the defer script from the jquery.js itself,  only that one,  the rest of the JS defers.   Because plugins like facetwp have jquery which executes inline instead of in a file.
